### ISSUE TITLE
作者您好！请问可以增加打印条形吗？

### ISSUE THREAD

**Issue by ponymuch** [LiuSky/XBPrint#1]
我用了您的SDK，写的很不错，但是打印QRCode有点问题。我这边需要打印条形码，如果可以交流一下的话，非常感谢。

**Comment by LiuSky** [comment]
你二维码出现什么问题？我这个库没怎么更新了。有空我会更新一波。

**Comment by ponymuch** [comment]
二维码打印出来是空的.其他都没问题。我这边对比了命令，是没问题的，可能是传输的字节有问题？我用的群索5803打印机。感谢回复。

**Comment by LiuSky** [comment]
你可以试下直接把传输子节修改为20试试看？

**Comment by ponymuch** [comment]
具体是哪一个呢？方便的话能加QQ联系吗？

**Comment by ponymuch** [comment]
我这边有打印指令，应该是字符串转换为字节data的过程中出现了问题。

**Comment by LiuSky** [comment]
嗯。解决了吗？解决了可以关闭掉这个issues
